### ISSUE TITLE
Segmentation Fault KLUSOLVE

### ISSUE THREAD

**Issue by adambomandel** [flaport/klujax#2]
Hey there, 

I have been trying to use `KLUJAX` in a topology optimization algorithm, where I need to find the `jax.grad` of a function called `obj_fun` which solves a large sparse matrix system using `KLUJAX`. I am unfortunately receiving a **segmentation fault**. I have tried increasing the allocated memory and I have attempted to track the fault and found it fails in a `JAX` function here: 
>python3.9/site-packages/jax/_src/dispatch.py:895.

Any ideas how to approach this? Thanks!

Best,
Adam
```
import numpy as np
import jax.numpy as jnp
from jax import value_and_grad
from jax.experimental import sparse as jsparse
from klujax import solve as klusolve
import sys
sys.settrace

def trace(frame, event, arg):
    print("%s, %s:%d" % (event, frame.f_code.co_filename, frame.f_lineno))
    return trace

def main():

  nelx=60
  nely=20
  volfrac=0.3
  rmin=1.5
  penal=6.0

  Emin=1e-9
  Emax=1.0

  ndof = 2*(nelx+1)*(nely+1)

  H, Hs = h_build(nelx, nely, rmin)
  ijK,edofMat = buildstiff_index(nelx,nely)

  x=volfrac * jnp.ones(nely*nelx,dtype=float)
  xold = jnp.copy(x)
  xPhys = jnp.copy(x)
  g=0 # must be initialized to use the NGuyen/Paulino OC approach
  dofs=np.arange(2*(nelx+1)*(nely+1))
  fixed=np.union1d(dofs[0:2*(nely+1):2],np.array([2*(nelx+1)*(nely+1)-1]))
  free=np.setdiff1d(dofs,fixed)
  f=np.zeros((ndof,1))
  f[1,0]=-1
  loop=0
  change=1
  while change>0.01 and loop<50:
    loop=loop+1
    print(loop)

    (obj, dc) = value_and_grad(obj_fun, argnums=0)(xPhys,x,nelx,nely,free,penal,Emax,Emin,fixed,f,H,Hs,edofMat,ijK)

    dv = np.ones(nely*nelx)
    dv[:] = np.asarray(H*(dv[np.newaxis].T/Hs))[:,0]

    xold = jnp.copy(x)
    (x_holder,g)=oc(nelx,nely,x,volfrac,dc,dv,g)
    x = x.at[:].set(x_holder)

    change=np.linalg.norm(x.reshape(nelx*nely,1)-xold.reshape(nelx*nely,1),np.inf)
    # Write iteration history to screen (req. Python 2.6 or newer)
    print("it.: {0} , obj.: {1:.3f} Vol.: {2:.3f}, ch.: {3:.3f}".format(\
          loop,obj,(g+volfrac*nelx*nely)/(nelx*nely),change))

def obj_fun(xPhys,x,nelx,nely,free,penal,Emax,Emin,fixed,f,H,Hs,edofMat,ijK): 
  ndof = 2*(nelx+1)*(nely+1)
  u=np.zeros((ndof,1))
  ce=np.ones(nelx*nely)
  xPhys=np.asarray(jsparse.bcoo_multiply_dense(H,x[np.newaxis].T/Hs))[:]
  K,KE = buildstiff(xPhys,penal,Emax,Emin,ndof,ijK)
  B = f[free, 0]
  u[free,0] = klusolve(K.indices[:,0],K.indices[:,1],K.data,B)
  ce[:] = (np.dot(u[edofMat].reshape(nelx*nely,8),KE) * u[edofMat].reshape(nelx*nely,8) ).sum(1)
  obj=( (Emin+xPhys**penal*(Emax-Emin))*ce )
  return obj.sum()

def buildstiff_index(nelx,nely):
  edofMat=np.zeros((nelx*nely,8),dtype=int)
  for elx in range(nelx):
    for ely in range(nely):
      el = ely+elx*nely
      n1=(nely+1)*elx+ely
      n2=(nely+1)*(elx+1)+ely
      edofMat[el,:]=np.array([2*n1+2, 2*n1+3, 2*n2+2, 2*n2+3,2*n2, 2*n2+1, 2*n1, 2*n1+1])
  ijK = np.vstack((np.kron(edofMat,np.ones((8,1))).flatten().astype(int),np.kron(edofMat,np.ones((1,8))).flatten().astype(int))).T
  return ijK,edofMat

def buildstiff(xPhys,penal,Emax,Emin,ndof,ijK):
  KE=lk()
  sK=((KE.flatten()[np.newaxis]).T*(Emin+(xPhys)**penal*(Emax-Emin))).flatten(order='F')
  K = jsparse.BCOO((sK,ijK),shape=(ndof,ndof))
  return K,KE

def h_build(nelx,nely,rmin):
  nfilter=int(nelx*nely*((2*(np.ceil(rmin)-1)+1)**2))
  ijH = np.zeros((nfilter,2)).astype(int)
  sH = np.zeros(nfilter).astype(int)
  cc=0
  for i in range(nelx):
    for j in range(nely):
      row=i*nely+j
      kk1=int(np.maximum(i-(np.ceil(rmin)-1),0))
      kk2=int(np.minimum(i+np.ceil(rmin),nelx))
      ll1=int(np.maximum(j-(np.ceil(rmin)-1),0))
      ll2=int(np.minimum(j+np.ceil(rmin),nely))
      for k in range(kk1,kk2):
        for l in range(ll1,ll2):
          col=k*nely+l
          fac=rmin-np.sqrt(((i-k)*(i-k)+(j-l)*(j-l)))
          ijH[cc, 0]=row
          ijH[cc, 1]=col
          sH[cc]=np.maximum(0.0,fac)
          cc=cc+1
  H=jsparse.BCOO((sH, ijH), shape=(nelx*nely,nelx*nely))
  Hs=sH.sum().astype(float)
  return H,Hs

def oc(nelx,nely,x,volfrac,dc,dv,g):
	l1=0
	l2=1e9
	move=0.2
	xnew=np.zeros(nelx*nely)
	while (l2-l1)/(l1+l2)>1e-3:
		lmid=0.5*(l2+l1)
		xnew[:]= np.maximum(0.0,np.maximum(x-move,np.minimum(1.0,np.minimum(x+move,x*np.sqrt(-dc/dv/lmid)))))
		gt=g+np.sum((dv*(xnew-x)))
		if gt>0 :
			l1=lmid
		else:
			l2=lmid
	return (xnew,gt)

def deleterowcol(A, delrow, delcol):
	# Assumes that matrix is in symmetric csc form !
	m = A.shape[0]
	keep = np.delete (np.arange(0, m), delrow)
	A = A.at[:].set(A[keep, :])  
	keep = np.delete (np.arange(0, m), delcol)
	A = A.at[:].set(A[keep, :])
	return A   

def lk():
	E=1
	nu=0.3
	k=np.array([1/2-nu/6,1/8+nu/8,-1/4-nu/12,-1/8+3*nu/8,-1/4+nu/12,-1/8-nu/8,nu/6,1/8-3*nu/8])
	KE = E/(1-nu**2)*np.array([ [k[0], k[1], k[2], k[3], k[4], k[5], k[6], k[7]],
	[k[1], k[0], k[7], k[6], k[5], k[4], k[3], k[2]],
	[k[2], k[7], k[0], k[5], k[6], k[3], k[4], k[1]],
	[k[3], k[6], k[5], k[0], k[7], k[2], k[1], k[4]],
	[k[4], k[5], k[6], k[7], k[0], k[1], k[2], k[3]],
	[k[5], k[4], k[3], k[2], k[1], k[0], k[7], k[6]],
	[k[6], k[3], k[4], k[1], k[2], k[7], k[0], k[5]],
	[k[7], k[2], k[1], k[4], k[3], k[6], k[5], k[0]] ]);
	return (KE)

sys.settrace(trace)
main()
```

**Comment by flaport** [comment]
I am trying to run your code, but I get the following error:

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/flaport/test.py", line 153, in <module>
    main()
  File "/home/flaport/test.py", line 44, in main
    (obj, dc) = value_and_grad(obj_fun, argnums=0)(xPhys,x,nelx,nely,free,penal,Emax,Emin,fixed,f,H,Hs,edofMat,ijK)
  File "/home/flaport/test.py", line 63, in obj_fun
    K,KE = buildstiff(xPhys,penal,Emax,Emin,ndof,ijK)
  File "/home/flaport/test.py", line 87, in buildstiff
    K = jsparse.BCOO((sK,ijK),shape=(ndof,ndof))
  File "/home/flaport/.anaconda/envs/klujax/lib/python3.9/site-packages/jax/experimental/sparse/bcoo.py", line 2457, in __init__
    _validate_bcoo(self.data, self.indices, self.shape)
  File "/home/flaport/.anaconda/envs/klujax/lib/python3.9/site-packages/jax/experimental/sparse/bcoo.py", line 141, in _validate_bcoo
    raise ValueError(f"Invalid {data.shape=} for {nse=}, {n_batch=}, {n_dense=}")
ValueError: Invalid data.shape=(691200,) for nse=76800, n_batch=0, n_dense=0
```

This indicates that there is an error constructing the sparse tensor. Are you sure the code snipped you provided above is correct?

**Comment by flaport** [comment]
I am trying to run the code you provided, but I'm getting this error:

```
Traceback (most recent call last):
  File "/home/flaport/hey.py", line 151, in <module>
    main()
  File "/home/flaport/hey.py", line 44, in main
    (obj, dc) = value_and_grad(obj_fun, argnums=0)(xPhys,x,nelx,nely,free,penal,Emax,Emin,fixed,f,H,Hs,edofMat,ijK)
  File "/home/flaport/.anaconda/envs/klujax/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/flaport/.anaconda/envs/klujax/lib/python3.9/site-packages/jax/_src/api.py", line 735, in value_and_grad_f
    ans, vjp_py = _vjp(f_partial, *dyn_args, reduce_axes=reduce_axes)
  File "/home/flaport/.anaconda/envs/klujax/lib/python3.9/site-packages/jax/_src/api.py", line 2258, in _vjp
    out_primal, out_vjp = ad.vjp(
  File "/home/flaport/.anaconda/envs/klujax/lib/python3.9/site-packages/jax/_src/interpreters/ad.py", line 139, in vjp
    out_primals, pvals, jaxpr, consts = linearize(traceable, *primals)
  File "/home/flaport/.anaconda/envs/klujax/lib/python3.9/site-packages/jax/_src/interpreters/ad.py", line 128, in linearize
    jaxpr, out_pvals, consts = pe.trace_to_jaxpr_nounits(jvpfun_flat, in_pvals)
  File "/home/flaport/.anaconda/envs/klujax/lib/python3.9/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File "/home/flaport/.anaconda/envs/klujax/lib/python3.9/site-packages/jax/_src/interpreters/partial_eval.py", line 771, in trace_to_jaxpr_nounits
    jaxpr, (out_pvals, consts, env) = fun.call_wrapped(pvals)
  File "/home/flaport/.anaconda/envs/klujax/lib/python3.9/site-packages/jax/_src/linear_util.py", line 166, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/flaport/hey.py", line 64, in obj_fun
    K,KE = buildstiff(xPhys,penal,Emax,Emin,ndof,ijK)
  File "/home/flaport/hey.py", line 85, in buildstiff
    K = jsparse.BCOO((sK,ijK),shape=(ndof,ndof))
  File "/home/flaport/.anaconda/envs/klujax/lib/python3.9/site-packages/jax/experimental/sparse/bcoo.py", line 2457, in __init__
    _validate_bcoo(self.data, self.indices, self.shape)
  File "/home/flaport/.anaconda/envs/klujax/lib/python3.9/site-packages/jax/experimental/sparse/bcoo.py", line 141, in _validate_bcoo
    raise ValueError(f"Invalid {data.shape=} for {nse=}, {n_batch=}, {n_dense=}")
jax._src.traceback_util.UnfilteredStackTrace: ValueError: Invalid data.shape=(691200,) for nse=76800, n_batch=0, n_dense=0

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/flaport/hey.py", line 151, in <module>
    main()
  File "/home/flaport/hey.py", line 44, in main
    (obj, dc) = value_and_grad(obj_fun, argnums=0)(xPhys,x,nelx,nely,free,penal,Emax,Emin,fixed,f,H,Hs,edofMat,ijK)
  File "/home/flaport/hey.py", line 64, in obj_fun
    K,KE = buildstiff(xPhys,penal,Emax,Emin,ndof,ijK)
  File "/home/flaport/hey.py", line 85, in buildstiff
    K = jsparse.BCOO((sK,ijK),shape=(ndof,ndof))
  File "/home/flaport/.anaconda/envs/klujax/lib/python3.9/site-packages/jax/experimental/sparse/bcoo.py", line 2457, in __init__
    _validate_bcoo(self.data, self.indices, self.shape)
  File "/home/flaport/.anaconda/envs/klujax/lib/python3.9/site-packages/jax/experimental/sparse/bcoo.py", line 141, in _validate_bcoo
    raise ValueError(f"Invalid {data.shape=} for {nse=}, {n_batch=}, {n_dense=}")
ValueError: Invalid data.shape=(691200,) for nse=76800, n_batch=0, n_dense=0
```

Is this the same error you're getting? If it is, then it's not related to klujax...

**Comment by adambomandel** [comment]
Hey Flaport, thanks for getting back to me. Unfortanetly no, all I', getting is **segementation fault**. The error your getting looks fixable.. I'm wondering mine crashes before it even gets to the error your getting.

**Comment by flaport** [comment]
can you try installing from source? It's been a while since I built the library. Maybe there is a mismatch between your python version and the versions I built...

To install from source, first install the SuiteSparse libraries (if you're on linux, they're probably available through your package manager)

Then install pybind11:

```bash
pip install pybind11
```

Then install klujax from source:

```bash
pip install --no-binary :all: klujax
```

**Comment by adambomandel** [comment]
Thanks for getting back to me again. Good news is I found the error early this morning! Bad news is I've taken up your time. I apologize for that.

It turns out the `jax.experimential.bcoo.multiply_dense`, hasn't been written yet and was returning a very large matrix which clogged up the ram and gave the seg error. So you were very right in the error wasn't in `KLUJAX`.

Thanks again for looking into it. Happy days.

**Comment by flaport** [comment]
No worries! Good luck with your project! :)
